### ISSUE TITLE
Mal-formatting of announcements web file causes server crash

### ISSUE THREAD

**Issue by kaylahynes** [BuiltBrokenModding/Announcement-Mod#1]
If the announcements text file posted on the web is not formatted correctly, it will cause a server crash.
## Originally like this, causing crash

{"Welcome to MeepCraft!"}
{"Future announcements will go here."}
{"Remember to check out my Patreon page at http://meep.space/patreons",10s}
## Now like this, which works fine.

{"Welcome to MeepCraft!"}, {"Future announcements will go here."}, {"Remember to check out my Patreon page at http://meep.space/patreons", 10s}
## More info

http://meepmeep22.com/topics.txt

Server side crash report: https://www.irccloud.com/pastebin/raw/aTLEKSgz

Excuse the report not being through, this was done quickly, but provides necessary info.

**Comment by DarkGuardsman** [comment]
I updated the curse page to note it needs commas for separation. As well I'll release another version that prints an error instead of crashing.

**Comment by DarkGuardsman** [comment]
Fixed https://github.com/BuiltBrokenModding/Announcement-Mod/commit/948a44b36a0d1be86cfd5ff96652a392d8d8fa30
